// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package personsqlc

import (
	"time"
)

type Person struct {
	ID        int32
	Name      string
	BirthDate time.Time
	Email     string
}
